const designer = [
    {
        Boards: [],
        Favorites: [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        Hashtags: [
            {content: "고데기펌"},{content: "엘리자벳펌"}
        ],
        Images: [],
        StoreId: null,
        Surgeries: [],
        address: null,
        coupons: {
            couponPrice: null,
            couponlimit: null,
            couponContent: null,
            couponexpired: null
        },
        createdAt: "2022-02-04 14:44:36",
        home: "https://lo-we.kr/reservation/lowe_ain",
        id: 21,
        img: "https://lowe-image.s3.ap-northeast-2.amazonaws.com/original/16439534742371631171894143.png",
        introduction: "\t#시그니처컬러메이킹 #염색 #탈색 시그니처컬러 전문, 염색요정 아인쌤입니다 :)",
        login_id: "01049475154",
        name: "아인",
        normal_id: "아인",
        operating_time: null,
        password: "1234",
        rank: null,
        reserve_url: "https://m.booking.naver.com/booking/13/bizes/474204/items/3959486",
        sns: null,
        store: "홍대입구역점",
        store_id: null,
        updatedAt: "2022-02-04 14:44:36",
        user_state: 1,
        user_type: 1,
        visit_num: "25",
    },{
        Boards: [],
        Favorites: [],
        Hashtags: [
            {content: "고데기펌"},{content: "엘리자벳펌"}
        ],
        Images: [],
        StoreId: null,
        Surgeries: [],
        address: null,
        coupons: {
            couponPrice: null,
            couponlimit: null,
            couponContent: null,
            couponexpired: null
        },
        createdAt: "2022-02-04 14:44:36",
        home: "https://lo-we.kr/reservation/lowe_ain",
        id: 21,
        img: "https://lowe-image.s3.ap-northeast-2.amazonaws.com/original/16439534742371631171894143.png",
        introduction: "\t#시그니처컬러메이킹 #염색 #탈색 시그니처컬러 전문, 염색요정 아인쌤입니다 :)",
        login_id: "01049475154",
        name: "아인",
        normal_id: "아인",
        operating_time: null,
        password: "1234",
        rank: null,
        reserve_url: "https://m.booking.naver.com/booking/13/bizes/474204/items/3959486",
        sns: null,
        store: "홍대입구역점",
        store_id: null,
        updatedAt: "2022-02-04 14:44:36",
        user_state: 1,
        user_type: 1,
        visit_num: "25",
    },{
        Boards: [],
        Favorites: [],
        Hashtags: [
            {content: "고데기펌"},{content: "엘리자벳펌"}
        ],
        Images: [],
        StoreId: null,
        Surgeries: [],
        address: null,
        coupons: {
            couponPrice: null,
            couponlimit: null,
            couponContent: null,
            couponexpired: null
        },
        createdAt: "2022-02-04 14:44:36",
        home: "https://lo-we.kr/reservation/lowe_ain",
        id: 21,
        img: "https://lowe-image.s3.ap-northeast-2.amazonaws.com/original/16439534742371631171894143.png",
        introduction: "\t#시그니처컬러메이킹 #염색 #탈색 시그니처컬러 전문, 염색요정 아인쌤입니다 :)",
        login_id: "01049475154",
        name: "아인",
        normal_id: "아인",
        operating_time: null,
        password: "1234",
        rank: null,
        reserve_url: "https://m.booking.naver.com/booking/13/bizes/474204/items/3959486",
        sns: null,
        store: "홍대입구역점",
        store_id: null,
        updatedAt: "2022-02-04 14:44:36",
        user_state: 1,
        user_type: 1,
        visit_num: "25",
    },{
        Boards: [],
        Favorites: [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        Hashtags: [
            {content: "고데기펌"},{content: "엘리자벳펌"}
        ],
        Images: [],
        StoreId: null,
        Surgeries: [],
        address: null,
        coupons: {
            couponPrice: null,
            couponlimit: null,
            couponContent: null,
            couponexpired: null
        },
        createdAt: "2022-02-04 14:44:36",
        home: "https://lo-we.kr/reservation/lowe_ain",
        id: 21,
        img: "https://lowe-image.s3.ap-northeast-2.amazonaws.com/original/16439534742371631171894143.png",
        introduction: "\t#시그니처컬러메이킹 #염색 #탈색 시그니처컬러 전문, 염색요정 아인쌤입니다 :)",
        login_id: "01049475154",
        name: "아인",
        normal_id: "아인",
        operating_time: null,
        password: "1234",
        rank: null,
        reserve_url: "https://m.booking.naver.com/booking/13/bizes/474204/items/3959486",
        sns: null,
        store: "홍대입구역점",
        store_id: null,
        updatedAt: "2022-02-04 14:44:36",
        user_state: 1,
        user_type: 1,
        visit_num: "25",
    },{
        Boards: [],
        Favorites: [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        Hashtags: [
            {content: "고데기펌"},{content: "엘리자벳펌"}
        ],
        Images: [],
        StoreId: null,
        Surgeries: [],
        address: null,
        coupons: "",
        createdAt: "2022-02-04 14:44:36",
        home: "https://lo-we.kr/reservation/lowe_ain",
        id: 21,
        img: "https://lowe-image.s3.ap-northeast-2.amazonaws.com/original/16439534742371631171894143.png",
        introduction: "\t#시그니처컬러메이킹 #염색 #탈색 시그니처컬러 전문, 염색요정 아인쌤입니다 :)",
        login_id: "01049475154",
        name: "아인",
        normal_id: "아인",
        operating_time: null,
        password: "1234",
        rank: null,
        reserve_url: "https://m.booking.naver.com/booking/13/bizes/474204/items/3959486",
        sns: null,
        store: "홍대입구역점",
        store_id: null,
        updatedAt: "2022-02-04 14:44:36",
        user_state: 1,
        user_type: 1,
        visit_num: "25",
    }
]


export default designer;