const portfolio = [
    {
        id: 1,
        Hashtags: [{ id: 5007, content: "샌드펌" }, { id: 5007, content: "염색" }, { id: 5007, content: "스타일" }],
        img: "https://lowe-image.s3.ap-northeast-2.amazonaws.com/original/164387470319608.jpg",
        managerId: 2,
        manager_id: 2,
        Boards: [{
            id: 124,
            phone: "0",
            designer_name: "니지",
            store: "합정점",
            name: "[합정] 러블리 히피펌 ",
            content: "디자인컷 + 히피펌 + 케라틴단백질케어",
            addContent: "0",
            price: 150000,
            addPrice: "기장 추가 없음",
            category: 2,
            eventType: 1,
            eventPrice: 45,
            open: "1",
            time: "0",
            gender: 1,
            length: 3,
            thumbnail: "https://lowe-image.s3.ap-northeast-2.amazonaws.com/original/165225568598400.jpg",
            visit: 0,
            createdAt: "2022-05-06 12:04:06",
            updatedAt: "2022-05-11 16:56:13",
            ManagerId: 56,
        }],
    },
    {
        id: 2,
        Hashtags: [{ id: 5007, content: "샌드펌" }, { id: 5007, content: "염색" }, { id: 5007, content: "스타일" }],
        img: "https://lowe-image.s3.ap-northeast-2.amazonaws.com/original/164387470319608.jpg",
        managerId: 2,
        manager_id: 2,
        Boards: [{
            id: 124,
            phone: "0",
            designer_name: "니지",
            store: "합정점",
            name: "[합정] 러블리 히피펌 ",
            content: "디자인컷 + 히피펌 + 케라틴단백질케어",
            addContent: "0",
            price: 150000,
            addPrice: "기장 추가 없음",
            category: 2,
            eventType: 1,
            eventPrice: 45,
            open: "1",
            time: "0",
            gender: 1,
            length: 3,
            thumbnail: "https://lowe-image.s3.ap-northeast-2.amazonaws.com/original/165225568598400.jpg",
            visit: 0,
            createdAt: "2022-05-06 12:04:06",
            updatedAt: "2022-05-11 16:56:13",
            ManagerId: 56,
        }],
    },
    {
        id: 3,
        Hashtags: [{ id: 5007, content: "샌드펌" }, { id: 5007, content: "염색" }, { id: 5007, content: "스타일" }],
        img: "https://t1.daumcdn.net/cfile/tistory/24283C3858F778CA2E",
        managerId: 2,
        manager_id: 2,
        Boards: [{
            id: 124,
            phone: "0",
            designer_name: "니지",
            store: "합정점",
            name: "[합정] 러블리 히피펌 ",
            content: "디자인컷 + 히피펌 + 케라틴단백질케어",
            addContent: "0",
            price: 150000,
            addPrice: "기장 추가 없음",
            category: 2,
            eventType: 1,
            eventPrice: 45,
            open: "1",
            time: "0",
            gender: 1,
            length: 3,
            thumbnail: "https://lowe-image.s3.ap-northeast-2.amazonaws.com/original/165225568598400.jpg",
            visit: 0,
            createdAt: "2022-05-06 12:04:06",
            updatedAt: "2022-05-11 16:56:13",
            ManagerId: 56,
        }],
    },
    {
        id: 4,
        Hashtags: [{ id: 5007, content: "샌드펌" }, { id: 5007, content: "염색" }, { id: 5007, content: "스타일" }],
        img: "https://lowe-image.s3.ap-northeast-2.amazonaws.com/original/164387470319608.jpg",
        managerId: 2,
        manager_id: 2,
        Boards: [{
            id: 124,
            phone: "0",
            designer_name: "니지",
            store: "합정점",
            name: "[합정] 러블리 히피펌 ",
            content: "디자인컷 + 히피펌 + 케라틴단백질케어",
            addContent: "0",
            price: 150000,
            addPrice: "기장 추가 없음",
            category: 2,
            eventType: 1,
            eventPrice: 45,
            open: "1",
            time: "0",
            gender: 1,
            length: 3,
            thumbnail: "https://lowe-image.s3.ap-northeast-2.amazonaws.com/original/165225568598400.jpg",
            visit: 0,
            createdAt: "2022-05-06 12:04:06",
            updatedAt: "2022-05-11 16:56:13",
            ManagerId: 56,
        }],
    },
    {
        id: 5,
        Hashtags: [{ id: 5007, content: "데일리펌" }, { id: 5007, content: "염색" }, { id: 5007, content: "스타일" }],
        img: "https://lowe-image.s3.ap-northeast-2.amazonaws.com/original/164387470319608.jpg",
        managerId: 2,
        manager_id: 2,
        Boards: [{
            id: 124,
            phone: "0",
            designer_name: "니지",
            store: "합정점",
            name: "[합정] 러블리 히피펌 ",
            content: "디자인컷 + 히피펌 + 케라틴단백질케어",
            addContent: "0",
            price: 150000,
            addPrice: "기장 추가 없음",
            category: 2,
            eventType: 1,
            eventPrice: 45,
            open: "1",
            time: "0",
            gender: 1,
            length: 3,
            thumbnail: "https://lowe-image.s3.ap-northeast-2.amazonaws.com/original/165225568598400.jpg",
            visit: 0,
            createdAt: "2022-05-06 12:04:06",
            updatedAt: "2022-05-11 16:56:13",
            ManagerId: 56,
        }],
    },
    {
        id: 6,
        Hashtags: [{ id: 5007, content: "샌드펌" }, { id: 5007, content: "염색" }, { id: 5007, content: "스타일" }],
        img: "https://lowe-image.s3.ap-northeast-2.amazonaws.com/original/164387470319608.jpg",
        managerId: 2,
        manager_id: 2,
        Boards: [{
            id: 124,
            phone: "0",
            designer_name: "니지",
            store: "합정점",
            name: "[합정] 러블리 히피펌 ",
            content: "디자인컷 + 히피펌 + 케라틴단백질케어",
            addContent: "0",
            price: 150000,
            addPrice: "기장 추가 없음",
            category: 2,
            eventType: 1,
            eventPrice: 45,
            open: "1",
            time: "0",
            gender: 1,
            length: 3,
            thumbnail: "https://lowe-image.s3.ap-northeast-2.amazonaws.com/original/165225568598400.jpg",
            visit: 0,
            createdAt: "2022-05-06 12:04:06",
            updatedAt: "2022-05-11 16:56:13",
            ManagerId: 56,
        }],
    },
    {
        id: 7,
        Hashtags: [{ id: 5007, content: "샌드펌" }, { id: 5007, content: "염색" }, { id: 5007, content: "스타일" }],
        img: "https://www.codingfactory.net/wp-content/uploads/abc.jpg",
        managerId: 2,
        manager_id: 2,
        Boards: [{
            id: 124,
            phone: "0",
            designer_name: "니지",
            store: "합정점",
            name: "[합정] 러블리 히피펌 ",
            content: "디자인컷 + 히피펌 + 케라틴단백질케어",
            addContent: "0",
            price: 150000,
            addPrice: "기장 추가 없음",
            category: 2,
            eventType: 1,
            eventPrice: 45,
            open: "1",
            time: "0",
            gender: 1,
            length: 3,
            thumbnail: "https://lowe-image.s3.ap-northeast-2.amazonaws.com/original/165225568598400.jpg",
            visit: 0,
            createdAt: "2022-05-06 12:04:06",
            updatedAt: "2022-05-11 16:56:13",
            ManagerId: 56,
        }],
    },
    {
        id: 8,
        Hashtags: [{ id: 5007, content: "데일리펌" }, { id: 5007, content: "염색" }, { id: 5007, content: "스타일" }],
        img: "https://lowe-image.s3.ap-northeast-2.amazonaws.com/original/164387470319608.jpg",
        managerId: 2,
        manager_id: 2,
        Boards: [{
            id: 124,
            phone: "0",
            designer_name: "니지",
            store: "합정점",
            name: "[합정] 러블리 히피펌 ",
            content: "디자인컷 + 히피펌 + 케라틴단백질케어",
            addContent: "0",
            price: 150000,
            addPrice: "기장 추가 없음",
            category: 2,
            eventType: 1,
            eventPrice: 45,
            open: "1",
            time: "0",
            gender: 1,
            length: 3,
            thumbnail: "https://lowe-image.s3.ap-northeast-2.amazonaws.com/original/165225568598400.jpg",
            visit: 0,
            createdAt: "2022-05-06 12:04:06",
            updatedAt: "2022-05-11 16:56:13",
            ManagerId: 56,
        }],
    },
]


export default portfolio;